### PR TITLE
Fix missing dash in docker compose and missing system-so-far in call to start-db

### PR DESCRIPTION
**Pull request by maacl**

### CODE REVIEW

**Comment by Mertzenich** [comment]
You do not need the dash for docker compose: `docker compose up -d` and `docker-compose up -d` do the same thing.

**Comment by maacl** [comment]
docker compose fails on my machine, Ubuntu 22 under WSL.

**Comment by bowbahdoe** [comment]
You just need a newer version of docker https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/

**Comment by bowbahdoe** [comment]
For the other change, `start-db` doesn't need the `system` until the next step.

**Comment by maacl** [comment]
Ah, makes sense.

**Comment by maacl** [comment]
And then again maybe not. The version of docker you get with Ubuntu 22 LTS
does not support docker compose. I think that will be a common issue.

**Comment by maacl** [comment]
Yeah, I missed that. Sorry.

**Pull request closed without merging**
